const FLAGS: Record<string, string> = {
  Afghanistan: '🇦🇫',
  Albania: '🇦🇱',
  Algeria: '🇩🇿',
  Argentina: '🇦🇷',
  Armenia: '🇦🇲',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Azerbaijan: '🇦🇿',
  Bangladesh: '🇧🇩',
  Belgium: '🇧🇪',
  Bolivia: '🇧🇴',
  Brazil: '🇧🇷',
  Bulgaria: '🇧🇬',
  Cambodia: '🇰🇭',
  Canada: '🇨🇦',
  Chile: '🇨🇱',
  China: '🇨🇳',
  Colombia: '🇨🇴',
  'Costa Rica': '🇨🇷',
  Croatia: '🇭🇷',
  Cuba: '🇨🇺',
  'Czech Republic': '🇨🇿',
  Denmark: '🇩🇰',
  Ecuador: '🇪🇨',
  Egypt: '🇪🇬',
  Estonia: '🇪🇪',
  Ethiopia: '🇪🇹',
  Europe: '🇪🇺',
  Finland: '🇫🇮',
  France: '🇫🇷',
  Georgia: '🇬🇪',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Greece: '🇬🇷',
  Guatemala: '🇬🇹',
  Hungary: '🇭🇺',
  Iceland: '🇮🇸',
  India: '🇮🇳',
  Indonesia: '🇮🇩',
  Iran: '🇮🇷',
  Iraq: '🇮🇶',
  Ireland: '🇮🇪',
  Israel: '🇮🇱',
  Italy: '🇮🇹',
  Jamaica: '🇯🇲',
  Japan: '🇯🇵',
  Jordan: '🇯🇴',
  Kazakhstan: '🇰🇿',
  Kenya: '🇰🇪',
  Laos: '🇱🇦',
  Latvia: '🇱🇻',
  Lebanon: '🇱🇧',
  Lithuania: '🇱🇹',
  Malaysia: '🇲🇾',
  Mexico: '🇲🇽',
  Mongolia: '🇲🇳',
  Morocco: '🇲🇦',
  Myanmar: '🇲🇲',
  Nepal: '🇳🇵',
  Netherlands: '🇳🇱',
  'New Zealand': '🇳🇿',
  Nigeria: '🇳🇬',
  Norway: '🇳🇴',
  Pakistan: '🇵🇰',
  Panama: '🇵🇦',
  Peru: '🇵🇪',
  Philippines: '🇵🇭',
  Poland: '🇵🇱',
  Portugal: '🇵🇹',
  Romania: '🇷🇴',
  Russia: '🇷🇺',
  'Saudi Arabia': '🇸🇦',
  Serbia: '🇷🇸',
  Singapore: '🇸🇬',
  Slovakia: '🇸🇰',
  Slovenia: '🇸🇮',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  Spain: '🇪🇸',
  'Sri Lanka': '🇱🇰',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Taiwan: '🇹🇼',
  Tanzania: '🇹🇿',
  Thailand: '🇹🇭',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  Ukraine: '🇺🇦',
  'United Arab Emirates': '🇦🇪',
  'United Kingdom': '🇬🇧',
  USA: '🇺🇸',
  'United States': '🇺🇸',
  Uruguay: '🇺🇾',
  Uzbekistan: '🇺🇿',
  Venezuela: '🇻🇪',
  Vietnam: '🇻🇳',
}

export function getCountryFlag(country: string): string {
  return FLAGS[country] ?? '🌍'
}
