import {
  Sword,
  MessageCircle,
  Dice5,
  BookOpen,
  Briefcase,
  Bot,
  Heart,
  Shield,
  Scissors,
  Sparkles,
  Dumbbell,
  UtensilsCrossed,
  FlaskConical,
  Microscope,
  TrendingUp,
  Languages,
  Lightbulb,
  Wand2,
  Laugh,
  Film,
  Newspaper,
  Tag,
  PawPrint,
  Palette,
  Cloud,
  Sun,
  Droplets,
  Trophy,
  Cpu,
  Star,
  Globe,
  Monitor,
  Gamepad2,
  Play,
  Code,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export interface CategoryTheme {
  icon: LucideIcon
  iconClass: string      // icon colour
  iconBgClass: string    // icon pill background
  accentClass: string    // top border / ring accent
  cardBgClass: string    // subtle card tint
}

const THEMES: Record<string, CategoryTheme> = {
  'Anime & Manga': {
    icon: Sword,
    iconClass: 'text-violet-500',
    iconBgClass: 'bg-violet-100 dark:bg-violet-900/30',
    accentClass: 'border-t-violet-400',
    cardBgClass: 'hover:bg-violet-50/50 dark:hover:bg-violet-900/10',
  },
  'AskReddit Life Questions': {
    icon: MessageCircle,
    iconClass: 'text-slate-500',
    iconBgClass: 'bg-slate-100 dark:bg-slate-800/50',
    accentClass: 'border-t-slate-400',
    cardBgClass: 'hover:bg-slate-50/50 dark:hover:bg-slate-800/20',
  },
  'Board Games': {
    icon: Dice5,
    iconClass: 'text-amber-600',
    iconBgClass: 'bg-amber-100 dark:bg-amber-900/30',
    accentClass: 'border-t-amber-400',
    cardBgClass: 'hover:bg-amber-50/50 dark:hover:bg-amber-900/10',
  },
  'Books Worth Reading': {
    icon: BookOpen,
    iconClass: 'text-yellow-600',
    iconBgClass: 'bg-yellow-100 dark:bg-yellow-900/30',
    accentClass: 'border-t-yellow-400',
    cardBgClass: 'hover:bg-yellow-50/50 dark:hover:bg-yellow-900/10',
  },
  'Career & Job Search': {
    icon: Briefcase,
    iconClass: 'text-blue-500',
    iconBgClass: 'bg-blue-100 dark:bg-blue-900/30',
    accentClass: 'border-t-blue-400',
    cardBgClass: 'hover:bg-blue-50/50 dark:hover:bg-blue-900/10',
  },
  'ChatGPT & AI Tools': {
    icon: Bot,
    iconClass: 'text-cyan-500',
    iconBgClass: 'bg-cyan-100 dark:bg-cyan-900/30',
    accentClass: 'border-t-cyan-400',
    cardBgClass: 'hover:bg-cyan-50/50 dark:hover:bg-cyan-900/10',
  },
  "Crohn's Disease & IBD Support": {
    icon: Heart,
    iconClass: 'text-rose-500',
    iconBgClass: 'bg-rose-100 dark:bg-rose-900/30',
    accentClass: 'border-t-rose-400',
    cardBgClass: 'hover:bg-rose-50/50 dark:hover:bg-rose-900/10',
  },
  'D&D Character Builds': {
    icon: Shield,
    iconClass: 'text-purple-500',
    iconBgClass: 'bg-purple-100 dark:bg-purple-900/30',
    accentClass: 'border-t-purple-400',
    cardBgClass: 'hover:bg-purple-50/50 dark:hover:bg-purple-900/10',
  },
  'DIY & Crafts': {
    icon: Scissors,
    iconClass: 'text-orange-500',
    iconBgClass: 'bg-orange-100 dark:bg-orange-900/30',
    accentClass: 'border-t-orange-400',
    cardBgClass: 'hover:bg-orange-50/50 dark:hover:bg-orange-900/10',
  },
  'Fashion & Beauty': {
    icon: Sparkles,
    iconClass: 'text-pink-500',
    iconBgClass: 'bg-pink-100 dark:bg-pink-900/30',
    accentClass: 'border-t-pink-400',
    cardBgClass: 'hover:bg-pink-50/50 dark:hover:bg-pink-900/10',
  },
  'Fitness & Weight Gain': {
    icon: Dumbbell,
    iconClass: 'text-green-600',
    iconBgClass: 'bg-green-100 dark:bg-green-900/30',
    accentClass: 'border-t-green-400',
    cardBgClass: 'hover:bg-green-50/50 dark:hover:bg-green-900/10',
  },
  'Food & Cooking': {
    icon: UtensilsCrossed,
    iconClass: 'text-orange-500',
    iconBgClass: 'bg-orange-100 dark:bg-orange-900/30',
    accentClass: 'border-t-orange-400',
    cardBgClass: 'hover:bg-orange-50/50 dark:hover:bg-orange-900/10',
  },
  'Food Science & Nutrition': {
    icon: FlaskConical,
    iconClass: 'text-lime-600',
    iconBgClass: 'bg-lime-100 dark:bg-lime-900/30',
    accentClass: 'border-t-lime-400',
    cardBgClass: 'hover:bg-lime-50/50 dark:hover:bg-lime-900/10',
  },
  'Interesting Facts & Science': {
    icon: Microscope,
    iconClass: 'text-teal-600',
    iconBgClass: 'bg-teal-100 dark:bg-teal-900/30',
    accentClass: 'border-t-teal-400',
    cardBgClass: 'hover:bg-teal-50/50 dark:hover:bg-teal-900/10',
  },
  'Investing & Finance': {
    icon: TrendingUp,
    iconClass: 'text-emerald-600',
    iconBgClass: 'bg-emerald-100 dark:bg-emerald-900/30',
    accentClass: 'border-t-emerald-400',
    cardBgClass: 'hover:bg-emerald-50/50 dark:hover:bg-emerald-900/10',
  },
  'Language & Learning': {
    icon: Languages,
    iconClass: 'text-indigo-500',
    iconBgClass: 'bg-indigo-100 dark:bg-indigo-900/30',
    accentClass: 'border-t-indigo-400',
    cardBgClass: 'hover:bg-indigo-50/50 dark:hover:bg-indigo-900/10',
  },
  'Life Hacks & Productivity': {
    icon: Lightbulb,
    iconClass: 'text-yellow-500',
    iconBgClass: 'bg-yellow-100 dark:bg-yellow-900/30',
    accentClass: 'border-t-yellow-400',
    cardBgClass: 'hover:bg-yellow-50/50 dark:hover:bg-yellow-900/10',
  },
  'Magic: The Gathering': {
    icon: Wand2,
    iconClass: 'text-purple-600',
    iconBgClass: 'bg-purple-100 dark:bg-purple-900/30',
    accentClass: 'border-t-purple-500',
    cardBgClass: 'hover:bg-purple-50/50 dark:hover:bg-purple-900/10',
  },
  'Memes & Humor': {
    icon: Laugh,
    iconClass: 'text-yellow-500',
    iconBgClass: 'bg-yellow-100 dark:bg-yellow-900/30',
    accentClass: 'border-t-yellow-400',
    cardBgClass: 'hover:bg-yellow-50/50 dark:hover:bg-yellow-900/10',
  },
  'Movies & Film Recommendations': {
    icon: Film,
    iconClass: 'text-red-500',
    iconBgClass: 'bg-red-100 dark:bg-red-900/30',
    accentClass: 'border-t-red-400',
    cardBgClass: 'hover:bg-red-50/50 dark:hover:bg-red-900/10',
  },
  'News & Current Events': {
    icon: Newspaper,
    iconClass: 'text-blue-600',
    iconBgClass: 'bg-blue-100 dark:bg-blue-900/30',
    accentClass: 'border-t-blue-500',
    cardBgClass: 'hover:bg-blue-50/50 dark:hover:bg-blue-900/10',
  },
  'Other': {
    icon: Tag,
    iconClass: 'text-gray-500',
    iconBgClass: 'bg-gray-100 dark:bg-gray-800/50',
    accentClass: 'border-t-gray-400',
    cardBgClass: 'hover:bg-gray-50/50 dark:hover:bg-gray-800/20',
  },
  'Pets & Animal Care': {
    icon: PawPrint,
    iconClass: 'text-amber-600',
    iconBgClass: 'bg-amber-100 dark:bg-amber-900/30',
    accentClass: 'border-t-amber-500',
    cardBgClass: 'hover:bg-amber-50/50 dark:hover:bg-amber-900/10',
  },
  'Pixel Art & Animation': {
    icon: Palette,
    iconClass: 'text-violet-500',
    iconBgClass: 'bg-violet-100 dark:bg-violet-900/30',
    accentClass: 'border-t-violet-400',
    cardBgClass: 'hover:bg-violet-50/50 dark:hover:bg-violet-900/10',
  },
  'Salesforce Tips & Career': {
    icon: Cloud,
    iconClass: 'text-sky-500',
    iconBgClass: 'bg-sky-100 dark:bg-sky-900/30',
    accentClass: 'border-t-sky-400',
    cardBgClass: 'hover:bg-sky-50/50 dark:hover:bg-sky-900/10',
  },
  'Self-Improvement & Wellness': {
    icon: Sun,
    iconClass: 'text-teal-500',
    iconBgClass: 'bg-teal-100 dark:bg-teal-900/30',
    accentClass: 'border-t-teal-400',
    cardBgClass: 'hover:bg-teal-50/50 dark:hover:bg-teal-900/10',
  },
  'Skincare & Acne Treatment': {
    icon: Droplets,
    iconClass: 'text-rose-400',
    iconBgClass: 'bg-rose-100 dark:bg-rose-900/30',
    accentClass: 'border-t-rose-300',
    cardBgClass: 'hover:bg-rose-50/50 dark:hover:bg-rose-900/10',
  },
  'Sports Highlights & Memorable Moments': {
    icon: Trophy,
    iconClass: 'text-yellow-600',
    iconBgClass: 'bg-yellow-100 dark:bg-yellow-900/30',
    accentClass: 'border-t-yellow-500',
    cardBgClass: 'hover:bg-yellow-50/50 dark:hover:bg-yellow-900/10',
  },
  'Tech & Gadgets': {
    icon: Cpu,
    iconClass: 'text-blue-500',
    iconBgClass: 'bg-blue-100 dark:bg-blue-900/30',
    accentClass: 'border-t-blue-400',
    cardBgClass: 'hover:bg-blue-50/50 dark:hover:bg-blue-900/10',
  },
  'Tottenham Hotspur Fandom': {
    icon: Star,
    iconClass: 'text-sky-600',
    iconBgClass: 'bg-sky-100 dark:bg-sky-900/30',
    accentClass: 'border-t-sky-500',
    cardBgClass: 'hover:bg-sky-50/50 dark:hover:bg-sky-900/10',
  },
  'Travel & Destinations': {
    icon: Globe,
    iconClass: 'text-emerald-500',
    iconBgClass: 'bg-emerald-100 dark:bg-emerald-900/30',
    accentClass: 'border-t-emerald-400',
    cardBgClass: 'hover:bg-emerald-50/50 dark:hover:bg-emerald-900/10',
  },
  'TV Series Recommendations': {
    icon: Monitor,
    iconClass: 'text-indigo-500',
    iconBgClass: 'bg-indigo-100 dark:bg-indigo-900/30',
    accentClass: 'border-t-indigo-400',
    cardBgClass: 'hover:bg-indigo-50/50 dark:hover:bg-indigo-900/10',
  },
  'Video Game Recommendations': {
    icon: Gamepad2,
    iconClass: 'text-violet-600',
    iconBgClass: 'bg-violet-100 dark:bg-violet-900/30',
    accentClass: 'border-t-violet-500',
    cardBgClass: 'hover:bg-violet-50/50 dark:hover:bg-violet-900/10',
  },
  'Viral Videos & Entertainment': {
    icon: Play,
    iconClass: 'text-red-500',
    iconBgClass: 'bg-red-100 dark:bg-red-900/30',
    accentClass: 'border-t-red-400',
    cardBgClass: 'hover:bg-red-50/50 dark:hover:bg-red-900/10',
  },
  'Web Development & Programming': {
    icon: Code,
    iconClass: 'text-slate-600',
    iconBgClass: 'bg-slate-100 dark:bg-slate-800/50',
    accentClass: 'border-t-slate-500',
    cardBgClass: 'hover:bg-slate-50/50 dark:hover:bg-slate-800/20',
  },
  'Weird & WTF Content': {
    icon: Zap,
    iconClass: 'text-fuchsia-500',
    iconBgClass: 'bg-fuchsia-100 dark:bg-fuchsia-900/30',
    accentClass: 'border-t-fuchsia-400',
    cardBgClass: 'hover:bg-fuchsia-50/50 dark:hover:bg-fuchsia-900/10',
  },
}

const FALLBACK: CategoryTheme = {
  icon: Tag,
  iconClass: 'text-gray-500',
  iconBgClass: 'bg-gray-100 dark:bg-gray-800/50',
  accentClass: 'border-t-gray-400',
  cardBgClass: 'hover:bg-gray-50/50 dark:hover:bg-gray-800/20',
}

export function getCategoryTheme(name: string): CategoryTheme {
  return THEMES[name] ?? FALLBACK
}
