/**
 * Maps language names to their most representative flag emoji.
 * Falls back to a globe 🌐 for anything not listed.
 */
const FLAGS: Record<string, string> = {
  Afrikaans: '🇿🇦',
  Albanian: '🇦🇱',
  Amharic: '🇪🇹',
  Arabic: '🇸🇦',
  Armenian: '🇦🇲',
  Azerbaijani: '🇦🇿',
  Basque: '🇪🇸',
  Belarusian: '🇧🇾',
  Bengali: '🇧🇩',
  Bosnian: '🇧🇦',
  Bulgarian: '🇧🇬',
  Cantonese: '🇭🇰',
  Catalan: '🇪🇸',
  Chinese: '🇨🇳',
  Croatian: '🇭🇷',
  Czech: '🇨🇿',
  Danish: '🇩🇰',
  Dutch: '🇳🇱',
  Estonian: '🇪🇪',
  Filipino: '🇵🇭',
  Finnish: '🇫🇮',
  French: '🇫🇷',
  Galician: '🇪🇸',
  Georgian: '🇬🇪',
  German: '🇩🇪',
  Greek: '🇬🇷',
  Gujarati: '🇮🇳',
  Haitian: '🇭🇹',
  Hausa: '🇳🇬',
  Hebrew: '🇮🇱',
  Hindi: '🇮🇳',
  Hungarian: '🇭🇺',
  Icelandic: '🇮🇸',
  Indonesian: '🇮🇩',
  Irish: '🇮🇪',
  Italian: '🇮🇹',
  Japanese: '🇯🇵',
  Javanese: '🇮🇩',
  Kannada: '🇮🇳',
  Kazakh: '🇰🇿',
  Khmer: '🇰🇭',
  Korean: '🇰🇷',
  Kurdish: '🇮🇶',
  Kyrgyz: '🇰🇬',
  Lao: '🇱🇦',
  Latin: '🏛️',
  Latvian: '🇱🇻',
  Lithuanian: '🇱🇹',
  Macedonian: '🇲🇰',
  Malay: '🇲🇾',
  Malayalam: '🇮🇳',
  Maltese: '🇲🇹',
  Mandarin: '🇨🇳',
  Marathi: '🇮🇳',
  Mongolian: '🇲🇳',
  Nepali: '🇳🇵',
  Norwegian: '🇳🇴',
  Pashto: '🇦🇫',
  Persian: '🇮🇷',
  Polish: '🇵🇱',
  Portuguese: '🇵🇹',
  Punjabi: '🇮🇳',
  Romanian: '🇷🇴',
  Russian: '🇷🇺',
  Serbian: '🇷🇸',
  Sindhi: '🇵🇰',
  Sinhala: '🇱🇰',
  Slovak: '🇸🇰',
  Slovenian: '🇸🇮',
  Somali: '🇸🇴',
  Spanish: '🇪🇸',
  Swahili: '🇰🇪',
  Swedish: '🇸🇪',
  Tagalog: '🇵🇭',
  Tajik: '🇹🇯',
  Tamil: '🇮🇳',
  Telugu: '🇮🇳',
  Thai: '🇹🇭',
  Turkish: '🇹🇷',
  Turkmen: '🇹🇲',
  Ukrainian: '🇺🇦',
  Urdu: '🇵🇰',
  Uzbek: '🇺🇿',
  Vietnamese: '🇻🇳',
  Welsh: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  Yoruba: '🇳🇬',
  Zulu: '🇿🇦',
}

export function getLanguageFlag(language: string): string {
  return FLAGS[language] ?? '🌐'
}

export function formatLanguageOption(language: string): string {
  return `${getLanguageFlag(language)}  ${language}`
}
